In [3]:
import pandas as pd

In [5]:
df=pd.read_csv(r'C:\Users\Snehja Srivastava\Downloads\Sorted by Subject Code.csv')

In [6]:
df

,Summer Course Registration (June 2023) - Sorted by Subject Code\n\n,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,S.No.,Subject Code,Subject Title,Credits,Roll No.,Name,Course,Branch,Batch,Semester (Reappear),Current Grade,Official Email ID,Email ID provided by the Student,Mobile
1,1,BTPC-201,Microbiology,3,21111011,ARUSH PANCHAL,B.Tech,BIO TECHNOLOGY,2021,3rd,U Grade,arushp.bt.21@nitj.ac.in,arushpanchal@hotmail.com,8195927900
2,2,BTPC-201,Microbiology,3,21111025,n,B.Tech,BIO TECHNOLOGY,2021,3rd,U Grade,kethavathsn.bt.21@nitj.ac.in,kethavathsn.bt.21@nitj.ac.in,9704242627
3,3,BTPC-201,Microbiology,3,21111033,PREETPAL SINGH,B.Tech,BIO TECHNOLOGY,2021,3rd,U Grade,preetpals.bt.21@nitj.ac.in,preetpals.bt.21@nitj.ac.in,9878505764
4,4,BTPC-201,Microbiology,3,21111035,PUSHPINDER SINGH,B.Tech,BIO TECHNOLOGY,2021,3rd,U Grade,pushpinders.bt.21@nitj.ac.in,pushpindersingh5464@gmail.com,8360921229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099,1099,HM-517,Consumer Behaviour,NaN,21701035,TANUSHREE MANDAL,MBA,HUMANITIES AND MANAGEMENT,2021,3rd,U Grade,tanushreem.hm.21@nitj.ac.in,tanushreem.hm.21@nitj.ac.in,8249371284
1100,1100,HM-519,Marketing of Services,NaN,21701001,ABHIMANYU SINGH THAKUR,MBA,HUMANITIES AND MANAGEMENT,2021,3rd,U Grade,abhimanyust.hm.21@nitj.ac.in,abhimanyust.hm.21@nitj.ac.in,7018334407
1101,1101,HM-519,Marketing of Services,NaN,21701019,PRIKSHIT THAKUR,MBA,HUMANITIES AND MANAGEMENT,2021,3rd,U Grade,prikshitt.hm.21@nitj.ac.in,prikshitt.hm.21@nitj.ac.in,7018964114
1102,1102,HM-519,Marketing of Services,NaN,21701027,SHUVANSHU PRIYADARSHAN,MBA,HUMANITIES AND MANAGEMENT,2021,3rd,W Grade,shuvanshup.hm.21@nitj.ac.in,shuvanshup.hm.21@nitj.ac.in,9973799608
1103,1103,MB-552,Management of Financial Services and Institutions,3,21701003,ADITYA NARAYAN,MBA,HUMANITIES AND MANAGEMENT,2021,3rd,W Grade,adityan.hm.21@nitj.ac.in,adityan.hm.21@nitj.ac.in,9472222153

In [7]:
df.describe()

,Summer Course Registration (June 2023) - Sorted by Subject Code\n\n,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,1104,1104,1104,1078,1104,1104,1104,1104,1104,1104,1104,1104,1104,1104
unique,1104,234,219,5,613,599,5,19,6,9,4,613,613,613
top,S.No.,MEPC-309,Mechatronics,3,21110059,VISHWAJEET SINGH,B.Tech,MECHANICAL ENGINEERING,2021,3rd,U Grade,navpreet.tt.21@nitj.ac.in,navpreet.tt.21@nitj.ac.in,7717329737
freq,1,46,47,610,3,5,1008,221,470,354,1069,3,3,3

In [9]:
df.dtypes

Summer Course Registration (June 2023) - Sorted by Subject Code\n\n    object
Unnamed: 1                                                             object
Unnamed: 2                                                             object
Unnamed: 3                                                             object
Unnamed: 4                                                             object
Unnamed: 5                                                             object
Unnamed: 6                                                             object
Unnamed: 7                                                             object
Unnamed: 8                                                             object
Unnamed: 9                                                             object
Unnamed: 10                                                            object
Unnamed: 11                                                            object
Unnamed: 12                                                            object
Unnamed: 13                                                            object
dtype: object